import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(
    page_title="Supply Chain Dashboard",
    page_icon="📊",
    layout="wide"
)

# Load cleaned dataset
@st.cache_data
def load_data():
    return pd.read_csv("supply_chain_data.csv")

df = load_data()

# Title
st.title("📊 Supply Chain Performance Dashboard")
st.write(
    "Interactive dashboard for analyzing revenue, sales, inventory, "
    "shipping, manufacturing, transportation, and quality."
)

st.divider()

# Sidebar Filters
st.sidebar.header("🔎 Dashboard Filters")

product_options = sorted(df["Product type"].dropna().unique())
selected_products = st.sidebar.multiselect(
    "Product Type",
    product_options,
    default=product_options
)

transport_options = sorted(df["Transportation modes"].dropna().unique())
selected_transport = st.sidebar.multiselect(
    "Transportation Mode",
    transport_options,
    default=transport_options
)

inspection_options = sorted(df["Inspection results"].dropna().unique())
selected_inspection = st.sidebar.multiselect(
    "Inspection Result",
    inspection_options,
    default=inspection_options
)

supplier_options = sorted(df["Supplier name"].dropna().unique())
selected_suppliers = st.sidebar.multiselect(
    "Supplier",
    supplier_options,
    default=supplier_options
)

# Apply filters
filtered_df = df[
    (df["Product type"].isin(selected_products)) &
    (df["Transportation modes"].isin(selected_transport)) &
    (df["Inspection results"].isin(selected_inspection)) &
    (df["Supplier name"].isin(selected_suppliers))
].copy()

if filtered_df.empty:
    st.warning("No data available for the selected filters.")
    st.stop()

# KPI Cards
st.subheader("📌 Key Performance Indicators")

col1, col2, col3, col4 = st.columns(4)

total_revenue = filtered_df["Revenue generated"].sum()
total_sold = filtered_df["Number of products sold"].sum()
average_price = filtered_df["Price"].mean()
average_defect = filtered_df["Defect rates"].mean()

col1.metric("Total Revenue", f"{total_revenue:,.2f}")
col2.metric("Products Sold", f"{total_sold:,.0f}")
col3.metric("Average Price", f"{average_price:,.2f}")
col4.metric("Average Defect Rate", f"{average_defect:.2f}")

st.divider()

# Revenue by Product Type
st.subheader("💰 Revenue Generated by Product Type")

revenue_product = (
    filtered_df
    .groupby("Product type", as_index=False)["Revenue generated"]
    .sum()
    .sort_values("Revenue generated", ascending=False)
)

fig1 = px.bar(
    revenue_product,
    x="Product type",
    y="Revenue generated",
    title="Revenue Generated by Product Type",
    text_auto=".2s"
)

st.plotly_chart(fig1, use_container_width=True)

# Transportation Mode
st.subheader("🚚 Transportation Mode Analysis")

transport_data = (
    filtered_df["Transportation modes"]
    .value_counts()
    .reset_index()
)

transport_data.columns = ["Transportation modes", "Count"]

fig2 = px.bar(
    transport_data,
    x="Transportation modes",
    y="Count",
    title="Transportation Mode Distribution",
    text_auto=True
)

st.plotly_chart(fig2, use_container_width=True)

# Inspection Results
st.subheader("📋 Inspection Results")

inspection_data = (
    filtered_df["Inspection results"]
    .value_counts()
    .reset_index()
)

inspection_data.columns = ["Inspection results", "Count"]

fig3 = px.bar(
    inspection_data,
    x="Inspection results",
    y="Count",
    title="Inspection Results",
    text_auto=True
)

st.plotly_chart(fig3, use_container_width=True)

# Price vs Revenue
st.subheader("📈 Price and Revenue Relationship")

fig4 = px.scatter(
    filtered_df,
    x="Price",
    y="Revenue generated",
    color="Product type",
    hover_data=["SKU", "Number of products sold", "Supplier name"],
    title="Price vs Revenue Generated"
)

st.plotly_chart(fig4, use_container_width=True)

# Stock vs Sales
st.subheader("📦 Inventory and Sales Analysis")

fig5 = px.scatter(
    filtered_df,
    x="Stock levels",
    y="Number of products sold",
    color="Product type",
    hover_data=["SKU", "Revenue generated"],
    title="Stock Levels vs Number of Products Sold"
)

st.plotly_chart(fig5, use_container_width=True)

# Manufacturing Cost
st.subheader("🏭 Manufacturing Cost Analysis")

fig6 = px.box(
    filtered_df,
    x="Product type",
    y="Manufacturing costs",
    title="Manufacturing Cost by Product Type"
)

st.plotly_chart(fig6, use_container_width=True)

# Shipping Cost
st.subheader("🚢 Shipping Cost Analysis")

fig7 = px.box(
    filtered_df,
    x="Transportation modes",
    y="Shipping costs",
    title="Shipping Cost by Transportation Mode"
)

st.plotly_chart(fig7, use_container_width=True)

# Correlation Heatmap
st.subheader("🔗 Correlation Analysis")

numeric_columns = [
    "Price",
    "Number of products sold",
    "Revenue generated",
    "Stock levels",
    "Lead times",
    "Order quantities",
    "Shipping times",
    "Shipping costs",
    "Production volumes",
    "Manufacturing lead time",
    "Manufacturing costs",
    "Defect rates",
    "Costs"
]

available_numeric = [
    column for column in numeric_columns
    if column in filtered_df.columns
]

correlation = filtered_df[available_numeric].corr()

fig8 = px.imshow(
    correlation,
    text_auto=".2f",
    aspect="auto",
    title="Supply Chain Correlation Heatmap"
)

st.plotly_chart(fig8, use_container_width=True)

# Additional Metrics
st.subheader("📊 Additional Supply Chain Metrics")

col1, col2, col3, col4 = st.columns(4)

total_stock = filtered_df["Stock levels"].sum()
average_shipping_cost = filtered_df["Shipping costs"].mean()
average_manufacturing_cost = filtered_df["Manufacturing costs"].mean()
average_lead_time = filtered_df["Lead times"].mean()

col1.metric("Total Stock", f"{total_stock:,.0f}")
col2.metric("Avg Shipping Cost", f"{average_shipping_cost:,.2f}")
col3.metric("Avg Manufacturing Cost", f"{average_manufacturing_cost:,.2f}")
col4.metric("Avg Lead Time", f"{average_lead_time:,.2f}")

st.divider()

# Filtered Data
st.subheader("📋 Filtered Supply Chain Data")

st.dataframe(filtered_df, use_container_width=True)

# Download
csv = filtered_df.to_csv(index=False).encode("utf-8")

st.download_button(
    "⬇️ Download Filtered Data",
    data=csv,
    file_name="filtered_supply_chain_data.csv",
    mime="text/csv"
)

st.divider()

st.caption(
    "Week 5 Internship Project | "
    "Advanced Visualization and Interactive Dashboard Design"
)